debug: true
persistence: '@every 10s'
alist:
    - name: 默认
      endpoint: http://host.docker.internal
      token: alist-xxxx
jobs:
    - name: 追更
      alist: 0
      from: |-
        aliyun/媒体库/国产剧/目录1
        aliyun/媒体库/国产剧/目录2
      dest: /data/media/国产剧
      mode: alist_url
      spec: ""
      opts:
        deep: 1
        overwrite: true
        filters: (?i)^\.(mp4|avi|mkv|mov|webm|flv|wmv|3gp|mpeg|mpg|ts|rmvb)$
        refresh: true
        extra: (?i)^\.(nfo|ass|srt|ssa|sub|png|jpg)$
        interval: 1
      concurrency: 1
listen: :8080
emby:
    addr: http://youremby.com
    apiKey: xxx
    httpStrm:
        - enable: true
          match: /data/media
          actions:
            - type: replace
              args: host.docker.internal -> youremby.com
          transCode: false
          finalURL: true
    alistStrm:
        - enable: true
          match: /data/media
          actions:
            type: ""
            args: ""
          alist: 0
          transCode: false
          rawURL: false
log:
    level: 4
    path: logs/app.log
entrance: enter
